name: first_flutter
description: A new Flutter project.

# Minimum Flutter version
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase packages
  firebase_core: ^2.26.0
  cloud_firestore: ^4.10.0
  firebase_auth: ^5.13.0

  # Other dependencies
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
